server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        native:
          searchLocations: classpath:config/licensingservice,classpath:config/organizationservice
